config/routes.rb
Rails.application.routes.draw do

  root 'kindergartens#index'

  resources :kindergartens do
    resources :lessons
  end
  resources :lessons do
    resources :sutdents
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kindergarten.rb
class Kindergarten < ApplicationRecord
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_inclusion_of :open, in: [true, false]

  has_many :lessons
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  validates_presence_of :subject, :teacher

  belongs_to :kindergarten
  has_many :sutdents
end

app/models/sutdent.rb
class Sutdent < ApplicationRecord

  validates_presence_of :name
  belongs_to :lesson
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kindergartens_controller.rb
class KindergartensController < ApplicationController
  before_action :set_kindergarten, except: [:index, :new, :create]

  def index
    @kindergartens = Kindergarten.all
  end


  def new
    @kindergarten = Kindergarten.new
  end

  def create
    @kindergarten = Kindergarten.new(kindergarten_params)
    if @kindergarten.save
      flash[:success] = 'Kindergarten Created!'
      redirect_to kindergarten_path(@kindergarten)
    else
      flash[:error] = 'Fix errors and try again'
      render :new
    end

  end

  def update
    if @kindergarten.update(kindergarten_params)
      flash[:success] = 'kindergarten Updated!'
      redirect_to kindergarten_path(@kindergarten)
    else
      flash[:error] = 'kindergarten failed to update!'
      render :edit
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @kindergarten.destroy
    flash[:success] = 'kindergarten Deleted!'
    redirect_to kindergartens_path
  end

  private
  def kindergarten_params
    params.require(:kindergarten).permit(:name, :students, :open)
  end

  def set_kindergarten
    @kindergarten = Kindergarten.find(params[:id])
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_kindergarten
  before_action :set_lesson, only: [:edit, :update, :show, :destroy]

  def index
    @lessons = @kindergarten.lessons
  end

  def new
    @lesson = @kindergarten.lessons.new
  end

  def create
    @lesson = @kindergarten.lessons.new(lesson_params)
    if @lesson.save
      flash[:success] = 'Lesson Created!'
      redirect_to kindergarten_lesson_path(@kindergarten, @lesson)
    else
      flash[:error] = 'Fix errors and try again'
      render :new
    end
  end


  def edit
  end

  def update
    if @lesson.update(lesson_params)
      flash[:success] = 'Lesson Updated!'
      redirect_to kindergarten_lesson_path(@kindergarten, @lesson)
    else
      flash[:error] = 'Fix errors and try again'
      render :edit
    end
  end

  def show
  end

  def destroy
    @lesson.destroy
    flash[:success] = 'Lesson Successfully Deleted!'
    redirect_to kindergarten_lesson_path(@kindergarten)
  end

  def all

  end
  
  private
  def lesson_params
    params.require(:lesson).permit(:subject, :teacher, :bully, :bullied)
  end

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def set_kindergarten
    @kindergarten = Kindergarten.find(params[:kindergarten_id])
  end

end

app/controllers/sutdents_controller.rb
class SutdentsController < ApplicationController
  before_action :set_lesson
  before_action :set_sutdent, only: [:edit, :update, :show, :destroy]

  def index
    @sutdents = @lesson.sutdents
  end

  def new
    @sutdent = @lesson.sutdents.new
  end

  def create
    @sutdent = @lesson.sutdents.new(sutdent_params)
    if @sutdent.save
      flash[:success] = 'Student created!'
      redirect_to lesson_sutdent_path(@lesson, @sutdent)
    else
      flash[:error] = 'Failed to create!'
      redirect_to :new
    end
  end

  def edit
  end

  def update
    if @sutdent.update(sutdent_params)
      flash[:success] = 'Sutdent Updated!'
      redirect_to lesson_sutdent_path(@lesson, @sutdent)
    else
      flash[:error] = 'Failed to update!'
      render :edit
    end
  end

  def show
  end

  def destroy
    @sutdent.destroy
    flash[:success] = 'Sutdent Successfully Deleted!'
    redirect_to lesson_sutdents_path(@lesson)
  end

  private
  def sutdent_params
    params.require(:sutdent).permit(:name, :behaves)
  end

  def set_sutdent
    @sutdent = Sutdent.find(params[:id])
  end

  def set_lesson
    @lesson = Lesson.find(params[:lesson_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kindergartens_helper.rb
module KindergartensHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/sutdents_helper.rb
module SutdentsHelper
end

app/views/kindergartens/_form.html.erb
<div class="row">
  <%= form_for @kindergarten do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :students %>
    <%= f.number_field :students %>
    <%= f.label :open %>
    <%= f.select :open, options_for_select(['open', 'closed'])%>
    <%= f.submit 'save', class: 'btn' %>
  <% end %>
</div>

app/views/kindergartens/edit.html.erb
<h1>Edit Kindergarten: <%= @kindergarten.name%></h1>

<%= render(partial: 'form') %>

<div class="center">
  <%= link_to 'Home', root_path, class: 'btn' %>
</div>

app/views/kindergartens/index.html.erb
<h1>Kindergartens</h1>
<p>Home of all the kindergartens in town</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Students</th>
      <th>Is it Open?</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @kindergartens.each do |kinder| %>
    <tr>
      <td><%= kinder.name %></td>
      <td><%= kinder.students %></td>
      <td><%= kinder.open %></td>
      <td><%= link_to 'Show', kinder, class: 'btn' %></td>
      <td><%= link_to 'Edit', edit_kindergarten_path(kinder), class: 'btn' %></td>
      <td><%= link_to 'Delete', kinder, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %></td>
    </tr>
    <% end %>
  </tbody>
</table>


<hr/>
<div class="center">
  <%= link_to 'New Kindergarten', new_kindergarten_path, class: 'btn' %>
</div>

app/views/kindergartens/new.html.erb
<h1>Add New Kindergarten</h1>

<%= render(partial: 'form') %>

<div class="center">
  <%= link_to 'Home', root_path, class: 'btn' %>
</div>

app/views/kindergartens/show.html.erb
<h1><%= @kindergarten.name %></h1>

<div class="row">
  <div class="col s12 m12">
    <div class="card z-depth-0">
      <div class="card-content">
        <span class="card-title"><%= @kindergarten.name %></span>
        <p>Open: <%= @kindergarten.open %></p>
        <p>Number of students: <%= @kindergarten.students %></p>
      </div>
      <div class="card-action">
        <%= link_to 'Home', root_path, class: 'btn card-btn' %>
        <%= link_to 'Lessons', kindergarten_lessons_path(@kindergarten), class: 'btn card-btn' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="menu">
  <div class="nav-wrapper">
    <%= link_to 'Kindergartens', root_path, class: 'brand-logo title' %>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
      <li><%= link_to 'Lessons' %></li>
      <li><a href="#">students</a></li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,400" rel="stylesheet">
  </head>

  <body>
    <%= render(partial: 'layouts/navbar') %>

    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/lessons/_form.html.erb
<div class="row">
  <%= form_for [@kindergarten, @lesson] do |f| %>
    <%= f.label :subject %>
    <%= f.text_field :subject %>
    <%= f.label :teacher %>
    <%= f.text_field :teacher %>
    <%= f.label :bully %>
    <%= f.text_field :bully %>
    <%= f.label :bullied %>
    <%= f.text_field :bullied %>
    <%= f.submit 'save', class: 'btn' %>
  <% end %>
</div>

app/views/lessons/all.html.erb
<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Teacher</th>
      <th>Official Bully</th>
      <th>Official Bullied</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @kindergartens.lessons.each do |lesson| %>
    <tr>
      <td><%= lesson.subject %></td>
      <td><%= lesson.teacher %></td>
      <td><%= lesson.bully %></td>
      <td><%= lesson.bullied %></td>
      <td><%= link_to 'Show', kindergarten_lesson_path(@kindergarten, lesson), class: 'btn' %></td>
      <td><%= link_to 'Edit', edit_kindergarten_lesson_path(@kindergarten, lesson), class: 'btn' %></td>
      <td><%= link_to 'Delete', lesson, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/lessons/edit.html.erb
<h1><%= @kindergarten.name %></h1>
<h3>Edit Lesson</h3>

<%= render(partial: 'form') %>

<div class="center">
  <%= link_to 'Home', root_path, class: 'btn' %>
</div>

app/views/lessons/index.html.erb
<h1><%= @kindergarten.name %></h1>
<h3>Lessons</h3>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Teacher</th>
      <th>Official Bully</th>
      <th>Official Bullied</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @kindergarten.lessons.each do |lesson| %>
    <tr>
      <td><%= lesson.subject %></td>
      <td><%= lesson.teacher %></td>
      <td><%= lesson.bully %></td>
      <td><%= lesson.bullied %></td>
      <td><%= link_to 'Show', kindergarten_lesson_path(@kindergarten, lesson), class: 'btn' %></td>
      <td><%= link_to 'Edit', edit_kindergarten_lesson_path(@kindergarten, lesson), class: 'btn' %></td>
      <td><%= link_to 'Delete', lesson, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %></td>
    </tr>
    <% end %>
  </tbody>
</table>


<hr/>
<div class="center">
  <%= link_to 'New Lesson', new_kindergarten_lesson_path, class: 'btn' %>
</div>

app/views/lessons/new.html.erb
<h1><%= @kindergarten.name %></h1>
<h3>Add New Lesson</h3>

<%= render(partial: 'form') %>

<div class="center">
  <%= link_to 'Home', root_path, class: 'btn' %>
</div>

app/views/lessons/show.html.erb
<h1><%= @kindergarten.name %></h1>

<div class="row">
  <div class="col s12 m12">
    <div class="card z-depth-0">
      <div class="card-content">
        <span class="card-title"><%= @lesson.subject %></span>
        <p>Teacher: <%= @lesson.teacher %></p>
        <p>Official Bully: <%= @lesson.bully %></p>
        <p>Official Bullied: <%= @lesson.bullied %></p>
      </div>
      <div class="card-action">
        <%= link_to 'Home', root_path, class: 'btn card-btn' %>
        <%= link_to 'Students', lesson_sutdents_path(@lesson), class: 'btn card-btn' %>
      </div>
    </div>
  </div>
</div>

app/views/sutdents/_form.html.erb
<div class="row">
  <%= form_for [@lesson, @sutdent] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :behaves %>
    <%= f.select :behaves, options_for_select(['yes', 'no'])%>
    <%= f.submit 'save', class: 'btn' %>
  <% end %>
</div>

app/views/sutdents/edit.html.erb
<h1><%= @lesson.subject %></h1>
<h3>Edit Student</h3>

<%= render(partial: 'form') %>

<div class="center">
  <%= link_to 'Home', root_path, class: 'btn' %>
</div>

app/views/sutdents/index.html.erb
<h1><%= @lesson.subject %></h1>
<h3>Students</h3>

<table>
  <thead>
    <tr>
      <th>Student Name</th>
      <th>Behaves?</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @lesson.sutdents.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.behaves %></td>
      <td><%= link_to 'Show', lesson_sutdent_path(@lesson, student), class: 'btn' %></td>
      <td><%= link_to 'Edit', edit_lesson_sutdent_path(@lesson, student), class: 'btn' %></td>
      <td><%= link_to 'Delete', lesson_sutdent_path(@lesson, student), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %></td>
    </tr>
    <% end %>
  </tbody>
</table>


<hr/>
<div class="center">
  <%= link_to 'New Student', new_lesson_sutdent_path, class: 'btn' %>
  <!-- back to lessons not working -->
  <%= link_to 'Back to Lessons', kindergarten_lessons_path(@lesson), class: 'btn' %>
</div>

app/views/sutdents/new.html.erb
<h1><%= @lesson.subject %></h1>
<h3>Add Student</h3>

<%= render(partial: 'form') %>

<div class="center">
  <%= link_to 'Home', root_path, class: 'btn' %>
  <%= link_to 'Back to Lessons', kindergarten_lessons_path(@lesson), class: 'btn' %>
</div>

app/views/sutdents/show.html.erb
<h1><%= @lesson.subject %></h1>

<div class="row">
  <div class="col s12 m12">
    <div class="card z-depth-0">
      <div class="card-content">
        <span class="card-title"><%= @sutdent.name %></span>
        <p>Behaves?: <%= @sutdent.behaves %></p>
      </div>
      <div class="card-action">
        <%= link_to 'Home', root_path, class: 'btn card-btn' %>
        <%= link_to 'Students', lesson_sutdents_path(@lesson), class: 'btn card-btn' %>
      </div>
    </div>
  </div>
</div>